image: ubuntu

build:
  stage: build
  script:
    - apt update && apt install -y curl gnupg
    - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
    - doppler run -- ./bin/build.sh
