steps:
  - name: ubuntu
    entrypoint: bash
    args:
      - -c
      - apt-get update > /dev/null && 
        apt-get install -y curl gnupg > /dev/null &&
        (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh &&
        doppler secrets --only-names;
    secretEnv: ['DOPPLER_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/doppler-examples/secrets/DOPPLER_TOKEN/versions/latest                 
    env: DOPPLER_TOKEN
